name = "malfunction"
main = "_workerrr.js"
compatibility_date = "2023-10-25"

[[kv_namespaces]]
binding = "FILES"
id = "e9644c42f17342f1aec1b49af0245e34"
preview_id = "e9644c42f17342f1aec1b49af0245e34"

[site]
bucket = "./public"



